  
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file outputTemplate.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml